version: '3'

services:

  apache-php:
    container_name: guenterh/suzanne-php
    image: suzanne-php5
    networks:
      - suzanne_net

    ports:
      - 1100:80
    depends_on:
      - mysql

  mysql:
    container_name: guenterh/suzanne-mysql

    #image: mysql:5.6.29
    #command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    #command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8
    #command: --default-authentication-plugin=mysql_native_password --collation-server=utf8_general_ci
    build:
      context: ./mysql


    #command: --init-file /docker-entrypoint-initdb.d/archive62.sql
    volumes:
      #- ./init:/docker-  entrypoint-initdb.d/
      - ./startscripts:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql


    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=suzanne
      - MYSQL_PASSWORD=suzanne
      - MYSQL_DATABASE=suzanne
    networks:
      - suzanne_net


networks:
  suzanne_net:

volumes:
  data:

