<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: root
 * Date: Fri, 01 Sep 2006 18:07:05 +0200
 */

$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['autopasswd'] = 0;
$conf['superuser'] = 'root';
$conf['target']['interwiki'] = '_blank';
$conf['target']['extern'] = '_blank';
$conf['float_toc'] = '1';

@include(DOKU_CONF.'local.protected.php');

// end auto-generated content
