<?php
/**
 * Language labels for plugin "tx_gooffotoboek_pi1"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'next' => 'Next',
		'next_off' => 'No next page',
		'prev' => 'Previous',
		'prev_off' => 'No previous page',
		'index' => 'Index',
		'index_off' => 'No upper index',
		'up' => 'Up',
		'up_off' => 'No upper album',
		'nodir' => 'Directory could not be openened.',
		'thumb' => 'Thumbnails',
		'thumb_off' => 'Select an album to view thumbnails',
		'thumb_alt' => 'Small photo',
		'thumb_link_alt' => 'Click here to view the big photo',
		'single_alt' => 'Click on the photo for the original',
		'edit' => 'Edit',
		'save' => 'Save',
		'saveSelected' => 'Save selected',
		'cancel' => 'Cancel',
		'admin' => 'Administration',
		'clearone' => 'Clear files older than one day',
		'clearweek' => 'Clear files older than a week',
		'clearall' => 'Clear all cache files',
		'clearold' => 'Clear cache files from older versions',
		'clickgone' => 'Warning: clicking is clearing!',
		'deleted' => 'deleted',
		'files' => 'files',
		'startslide' => 'Start slideshow',
		'stopslide' => 'Stop slideshow',
		'default' => 'Default',
		'title' => 'Title',
		'comment' => 'Comment',
		'basketDisabled' => 'Basket function is disabled in the template.',
		'basket' => 'Basket',
		'basketAdd' => 'Add to basket',
		'basketEmpty' => 'Empty basket',
		'removeSelected' => 'Remove Selected',
		'removeItem' => 'Remove Item',
		'basketGetZip' => 'Get the Zipfile',
		'basketGenerateZip' => 'Generate the Zipfile',
		'basketIsEmpty' => 'There are no images in the basket',
		'basketCount' => 'Items : ',
		'basketZipGenerating' => 'Generating Zip file',
		'basketClose' => 'Close this popup',
		'added' => 'Added',
		'image' => 'Picture',
		'images' => 'pictures',
		'of' => 'of',





	),
	'dk' => Array (
		'next' => 'Næste',
		'prev' => 'Forige',
		'index' => 'Indhold',
		'up' => 'Op',
		'nodir' => 'Mappen kunne ikke åbnes.',
		'thumb' => 'Oversigt',
		'edit' => 'Redigere',
		'save' => 'Gem',
		'cancel' => 'Fortryd',
		'admin' => 'Administration',
		'clearone' => 'Clear files older than one day',
		'clearweek' => 'Clear files older than a week',
		'clearall' => 'Clear all cache files',
		'clearold' => 'Clear cache files from older versions',
		'clickgone' => 'Warning: clicking is clearing!',
		'deleted' => 'Slet',
		'files' => 'filer',
		'startslide' => 'Start diasshow',
		'stopslide' => 'Stop diasshow',
	),
	'de' => Array (
		'next' => 'Nächstes',
		'prev' => 'Vorheriges',
		'index' => 'Index',
		'up' => 'Hoch',
		'nodir' => 'Verzeichnis kann nicht geöffnet werden.',
		'thumb' => 'Vorschaubilder',
		'edit' => 'Bearbeiten',
		'save' => 'Speichern',
		'cancel' => 'Abbrechen',
		'admin' => 'Administration',
		'clearone' => 'Alle temporären Dateien, die älter als ein Tag 
sind löschen',
		'clearweek' => 'Alle temporären Dateien, die älter als eine 
Woche sind löschen',
		'clearall' => 'Alle temporären Dateien löschen',
		'clearold' => 'Alle temporären Dateien von alten Versionen löschen',
		'clickgone' => 'Warnung: Alle temporären Dateien werden gelöscht!',
		'deleted' => 'gelöscht',
		'files' => 'Dateien',
		'startslide' => 'Starte Slideshow',
		'stopslide' => 'Stoppe Slideshow',
		'image' => 'Bild',
		'images' => 'Bildern',
		'of' => 'von',
	),
	'no' => Array (
	),
	'it' => Array (
		'next' => 'Avanti',
		'prev' => 'Indietro',
		'index' => 'Indice',
		'up' => 'Su',
		'nodir' => 'Impossibile leggere il contenuto della cartella',
		'thumb' => 'Miniature',
		'edit' => 'Modifica',
		'save' => 'Salva',
		'cancel' => 'Cancella',
		'admin' => 'Amministrazione',
		'clearone' => 'Elimina file più vecchi di un giorno',
		'clearweek' => 'Elimina file più vecchi di una settimana',
		'clearall' => 'Pulisci tutta la cache',
		'clearold' => 'Pulisci la cache delle versioni più vecchie',
		'clickgone' => 'Warning: clicking is clearing!',
		'deleted' => 'Eliminato',
		'files' => 'File',
	),
	'fr' => Array (
		'next' => 'Suivant',
		'prev' => 'Précédent',
		'index' => 'Index',
		'up' => 'Remonter',
		'nodir' => "Le dossier n'a pu être ouvert.",
		'thumb' => 'Miniatures',
		'edit' => 'Editer',
		'save' => 'Enregistrer',
		'saveSelected' => 'Enregistrer les éléments sélectionnés',
		'cancel' => 'Annuler',
		'admin' => 'Administration',
		'clearone' => "Effacer les fichiers vieux d'au moins un jour",
		'clearweek' => "Effacer les fichiers vieux d'au moins une semaine",
		'clearall' => 'Effacer tous les fichiers du cache',
		'clearold' => 'Effacer les fichiers du cache des versions précédentes',
		'clickgone' => 'Attention : En cliquant, vous effacez !',
		'deleted' => 'effacé',
		'files' => 'fichiers',
		'startslide' => 'Démarrer le diaporama',
		'stopslide' => 'Arrêter le diaporama',
		'default' => 'Par défaut',
		'title' => 'Titre',
		'comment' => 'Commentaire',
		'basketDisabled' => 'La fonction de panier est désactivée dans le template.',
		'basket' => 'Panier',
		'basketAdd' => 'Ajouter au panier',
		'basketEmpty' => 'Vider le panier',
		'removeSelected' => 'Effacer les éléments sélectionnés',
		'removeItem' => "Effacer l'élément",
		'basketGetZip' => 'Récupérer le fichier zip',
		'basketGenerateZip' => 'Générer le fichier zip',
		'basketIsEmpty' => "Il n'a pas d'images dans le panier",
		'basketCount' => 'Eléments : ',
		'basketZipGenerating' => 'Generation du fichier zip',
		'basketClose' => 'Fermer cette fenêtre',
		'added' => 'Ajouté',
		'image' => 'Image',
		'images' => 'images',
		'of' => 'de',
	),
	'es' => Array (
	),
	'nl' => Array (
		'next' => 'Volgende',
		'next_off' => 'Er is geen volgende pagina',
		'prev' => 'Vorige',
		'prev_off' => 'Er is geen vorige pagina',
		'index' => 'Index',
		'index_off' => 'Er is geen bovenliggende index',
		'up' => 'Omhoog',
		'up_off' => 'Er is geen bovenliggend album',
		'nodir' => 'Directory kon niet geopend worden.',
		'thumb' => 'Miniaturen',
		'thumb_off' => 'Selecteer een album om de miniaturen te zien',
		'thumb_alt' => 'Kleine foto',
		'thumb_link_alt' => 'Klik op de afbeelding voor een vergrote versie',
		'single_alt' => 'Klik op de foto voor de orginele foto',
		'edit' => 'Wijzigen',
		'save' => 'Opslaan',
		'saveSelected' => 'Geselecteerde opslaan',
		'cancel' => 'Annuleren',
		'admin' => 'Beheer',
		'clearone' => 'Wis bestanden ouder dan een dag',
		'clearweek' => 'Wis bestanden ouder dan een week',
		'clearall' => 'Wis alle tijdelijke bestanden',
		'clearold' => 'Wis bestanden van oudere versies',
		'clickgone' => 'Waarschuwing: Klikken is wissen!',
		'deleted' => 'verwijderd',
		'files' => 'bestanden',
		'startslide' => 'Start slideshow',
		'stopslide' => 'Stop slideshow',
		'default' => 'Standaard',
		'title' => 'Titel',
		'comment' => 'Commentaar',
		'basketDisabled' => 'Mandje is uitgeschakeld in het template.',
		'basketAdd' => 'Aan mandje toevoegen',
		'basket' => 'Mandje',
		'basketEmpty' => 'Mandje leegmaken',
		'image' => 'Foto',
		'images' => "foto's",
		'of' => 'van',
	),
	'cz' => Array (
	),
	'pl' => Array (
		'next' => 'Nast&#281;pny',
		'prev' => 'Poprzedni',
		'index' => 'Indeks',
		'up' => 'Do góry',
		'nodir' => 'Nie mo¿na otwiorzyæ katalogu',
		'thumb' => 'Miniatury',
	),
	'si' => Array (
	),
	'fi' => Array (
		'next' => 'Seuraava',
		'prev' => 'Edellinen',
		'index' => 'Indeksi',
		'up' => 'Ylös',
		'nodir' => 'Hakemistoa ei voitu avata',
		'thumb' => 'Pienennökset',
		'edit' => 'Muotoile',
		'save' => 'Tallenna',
		'saveSelected' => 'Tallenna valitut',
		'cancel' => 'Peruuta',
		'admin' => 'Hallinta',
		'clearone' => 'Poista yhtä päivää vanhemmat tiedostot',
		'clearweek' => 'Poista viikkoa vanhemmat tiedostot',
		'clearall' => 'Poista kaikki tiedostot välimuistista',
		'clearold' => 'Poista välimuistista tiedostot vanhemmista versioista',
		'clickgone' => 'Varoitus: näpsäytys tekee poiston !',
		'deleted' => 'poistettu',
		'files' => 'tiedostoa',
		'startslide' => 'Aloita kuvien näyttö',
		'stopslide' => 'Lopeta kuvien näyttö',
		'default' => 'Oletus',
		'title' => 'Otsikko',
		'comment' => 'Kommentti',
	),
	'tr' => Array (
	),
	'se' => Array (
		'next' => 'Nästa',
		'prev' => 'Föregående',
		'index' => 'Index',
		'up' => 'Upp',
		'nodir' => 'Katalogen gick inte att öppna',
		'thumb' => 'Små bilder',
		'edit' => 'Ändra',
		'save' => 'Spara',
		'cancel' => 'Avbryt',
		'admin' => 'Administration',
		'clearone' => 'Töm filer som är äldre än en dag',
		'clearweek' => 'Töm filer som är äldre än en vecka',
		'clearall' => 'Töm alla filer i mellanminnet',
		'clearold' => 'Töm alla filer i mellanminnet från äldre versioner',
		'clickgone' => 'Varning: genom att klicka tömmer du minnet!',
		'deleted' => 'raderade',
		'files' => 'filer',
		'startslide' => 'Starta diavisning',
		'stopslide' => 'Stoppa diavisning',
	),
	'pt' => Array (
	),
	'ru' => Array (
		'next' => 'Ñëåäóþùèé',
		'next_off' => 'Íåò ñëåäóþùåé ñòðàíèöû',
		'prev' => 'Ïðåäûäóùèé',
		'prev_off' => 'Íåò ïðåäûäóùåé ñòðàíèöû',		
		'index' => 'Èíäåêñ',
		'index_off' => 'Íåò èíäåêñà âûøå',
		'up' => 'Íàâåðõ',
		'up_off' => 'Íåò àëüáîìîâ âûøå',		
		'nodir' => 'Ïàïêà íå ìîæåò áûòü îòêðûòà.',		
		'thumb' => 'Ñïèñîê èçîáðàæåíèé',		
		'thumb_off' => 'Âûáðàíûé àëüáîì îòîáðàæàåò ñïèñîê èçîáðàæåíèé',		
		'thumb_alt' => 'Ìàëûå ôîòîãðàôèè',
		'thumb_link_alt' => 'Íàæìèòå çäåñü äëÿ ïðîñìîòðà áîëüøèõ ôîòîãðàôèé',
		'single_alt' => 'Íàæìèòå íà ôîòîãðàôèþ äëÿ ïîëó÷åíèÿ îðèãèíàëà',
		'edit' => 'Ðåäàêòèðîâàòü',
		'save' => 'Ñîõðàíèòü',
		'saveSelected' => 'Ñîõðàíèòü âûáðàííîå',
		'cancel' => 'Îòìåíà',
		'admin' => 'Àäìèíèñòðèðîâàíèå',
		'clearone' => 'Î÷èñòèòü ôàéëû ñòàðøå îäíîãî äíÿ',
		'clearweek' => 'Î÷èñòèòü ôàéëû ñòàðøå ñåìè äíåé',
		'clearall' => 'Î÷èñòèòü âñå çàêåøèðîâàíûå ôàéëû',
		'clearold' => 'Î÷èñòèòü êýø ñî âñåõ ñòàðûõ âåðñèé',
		'clickgone' => 'Âíèìàíèå: ïîäòâåðæåíèå ïðèâåä¸ò ê óäàëåíèþ ôàéëà!',
		'deleted' => 'óäàëåíî',
		'files' => 'ôàéëû',
		'startslide' => 'Íà÷àòü ñëàéäøîó',
		'stopslide' => 'Îñòàíîâèòü ñëàéäøîó',
		'default' => 'Ïî óìîë÷àíèþ',
		'title' => 'Çàãîëîâîê',
		'comment' => 'Êîììåíòàðèé',
		'basketDisabled' => 'Ôóíêöèÿ êîðçèíû îòêëþ÷åíà â øàáëîíå.',
		'basket' => 'Êîðçèíà',
		'basketAdd' => 'Äîáàâèòü â êîðçèíó',
		'basketEmpty' => 'Î÷èñòèòü êîðçèíó',
		'removeSelected' => 'Óäàëèòü âûáðàííûå',
		'removeItem' => 'Óäàëèòü ýëåìåíò',
		'basketGetZip' => 'Ïîëó÷èòü Zip-ôàéë',
		'basketGenerateZip' => 'Ãåíåðèðîâàòü Zip-ôàéë',
		'basketIsEmpty' => 'Íåò èçîáðàæåíèé â êîðçèíå',
		'basketCount' => 'Ýëåìåíòû : ',
		'basketZipGenerating' => 'Ãåíåðàöèÿ Zip ôàéëà',
		'basketClose' => 'Çàêðûòü âñïëûòèå',
		'added' => 'Äîáàâëåí',
		'image' => 'Êàðòèíà',
		'images' => 'êàðòèíîê',
		'of' => 'ñ',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
		'next' => 'Következõ',
		'prev' => 'Elõzõ',
		'index' => 'Index',
		'up' => 'Fel',
		'nodir' => 'A könyvtárat nem lehet megnyitni.',
		'thumb' => 'Kisképek',
		'edit' => 'Szerkesztés',
		'save' => 'Mentés',
		'cancel' => 'Mégse',
		'admin' => 'Adminsztráció',
		'clearone' => 'Egy napnál régebbi file-ok törlése',
		'clearweek' => 'Egy hétnél régebbi file-ok törlése',
		'clearall' => 'Összes cache file törlése',
		'clearold' => 'Régebbi verziójú cache file-ok törlése',
		'clickgone' => 'Figyelem: a klikkelés törlést jelent!',
		'deleted' => 'törölve',
		'files' => 'file',
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'next' => 'Próxima',
		'prev' => 'Anterior',
		'index' => 'Índice',
		'up' => 'Acima',
		'nodir' => 'Não foi possível abrir o diretório.',
		'thumb' => 'Miniaturas',
		'edit' => 'Editar',
		'save' => 'Salvar',
		'saveSelected' => 'Salvar selecionados',
		'cancel' => 'Cancelar',
		'admin' => 'Administração',
		'clearone' => 'Remover arquivos com mais de um dia',
		'clearweek' => 'Remover arquivos com mais de uma semana',
		'clearall' => 'Remover todos os arquivos do cache',
		'clearold' => 'Remover arquivos de cache de versões antigas',
		'clickgone' => 'Atenção: clicar é limpar!',
		'deleted' => 'apagado',
		'files' => 'arquivos',
		'startslide' => 'Iniciar exibição de slides',
		'stopslide' => 'Parar exibição de slides',
		'default' => 'Padrão',
		'title' => 'Título',
		'comment' => 'Comentário',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
		'next' => 'Íàñòóïíèé',
		'next_off' => 'Íåìàº íàñòóïíî¿ ñòîð³íêè',
		'prev' => 'Ïîïåðåäí³é',
		'prev_off' => 'Íåìàº ïîïåðåäíüî¿ ñòîð³íêè',		
		'index' => '²íäåêñ',
		'index_off' => 'Íåìàº ³íäåêñó âèùå',
		'up' => 'Íàãîðó',
		'up_off' => 'Íåìàº àëüáîì³â âèùå',		
		'nodir' => 'Äèðåêòîð³ÿ íå ìîæå áóòè â³äêðèòà.',		
		'thumb' => 'Ïåðåë³ê çîáðàæåíü',		
		'thumb_off' => 'Âèáðàíèé àëüáîì â³äîáðàæàº ïåðåë³ê çîáðàæåíü',		
		'thumb_alt' => 'Ìàë³ ôîòîãðàô³¿',
		'thumb_link_alt' => 'Íàòèñí³òü òóò äëÿ ïåðåãëÿäó âåëèêèõ ôîòîãðàô³é',
		'single_alt' => 'Íàòèñí³òü íà ôîòîãðàô³þ äëÿ îòðèìàííÿ îðèã³íàëó',
		'edit' => 'Ðåäàãóâàòè',
		'save' => 'Çáåðåãòè',
		'saveSelected' => 'Çáåðåãòè âèáðàí³',
		'cancel' => 'Ñêàñóâàòè',
		'admin' => 'Àäì³í³ñòðóâàííÿ',
		'clearone' => 'Î÷èñòèòè ôàéëè ñòàð³øå îäíîãî äíÿ',
		'clearweek' => 'Î÷èñòèòè ôàéëè ñòàð³øå ñåìè äí³â',
		'clearall' => 'Î÷èñòèòè âñ³ çàêåøîâàí³ ôàéëè',
		'clearold' => 'Î÷èñòèòè êåø ç óñ³õ ñòàðèõ âåðñ³é',
		'clickgone' => 'Óâàãà: ï³äòâåðäæåííÿ ïðèâåäå äî âèäàëåííÿ ôàéëó!',
		'deleted' => 'âèäàëåíî',
		'files' => 'ôàéëè',
		'startslide' => 'Ïî÷àòè ñëàéäøîó',
		'stopslide' => 'Çóïèíèòè ñëàéäøîó',
		'default' => 'Ïî çàìîâ÷åíþ',
		'title' => 'Çàãîëîâîê',
		'comment' => 'Êîìåíòàð',
		'basketDisabled' => 'Ôóíêö³þ êîøèêà âèìêíåíî ó øàáëîí³.',
		'basket' => 'Êîøèê',
		'basketAdd' => 'Äîäàòè ó êîøèê',
		'basketEmpty' => 'Î÷èñòèòè êîøèê',
		'removeSelected' => 'Âèäàëèòè îáðàí³',
		'removeItem' => 'Âèäàëèòè åëåìåíò',
		'basketGetZip' => 'Îòðèìàòè Zip-ôàéë',
		'basketGenerateZip' => 'Ãåíåðóâàòè Zip-ôàéë',
		'basketIsEmpty' => 'Íåìàº çîáðàæåíü ó êîøèêó',
		'basketCount' => 'Åëåìåíòè : ',
		'basketZipGenerating' => 'Ãåíåðàö³ÿ Zip ôàéëó',
		'basketClose' => 'Çàêðèòè ñïëèòòÿ',
		'added' => 'Äîäàíî',
		'image' => 'Êàðòèíà',
		'images' => 'êàðòèíîê',
		'of' => 'ç',
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>
